name: pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/initialcapacity/flask-jumpstart
          cacheFrom: ghcr.io/initialcapacity/flask-jumpstart
          push: always
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/initialcapacity/flask-jumpstart
          runCmd: |
            python -m unittest  
